### ISSUE TITLE
Any news about the methods?

### ISSUE THREAD

**Issue by rafaeleyng** [mayognaise/aframe-gif-shader#1]
Hello there. Awesome job!

The README states:

> Method
> 
> The following method is coming soon.
> 
> play()
> pause()
> togglePlayback()
> nextFrame()
> paused()

Any news about this? I'd gladly use those methods in my current project.

**Comment by mayognaise** [comment]
@rafaeleyng hello! ahh sorry i havent touched for a while. I'll add it now 🍡

**Comment by rafaeleyng** [comment]
@mayognaise Nice, that would be life saving 👍

**Comment by mayognaise** [comment]
@rafaeleyng sorry i was lazy in the weekend..
I just pushed as 0.1.7. pls install again.
and let me know if you have any questions!

**Comment by rafaeleyng** [comment]
@mayognaise will try it ASAP. Thanks a lot!

**Comment by mayognaise** [comment]
hi @rafaeleyng, i talked with aframe team and it's not good to have methods in shader side.
ill rewrite this tonight. so pls stay tuned.

**Comment by rafaeleyng** [comment]
Are you removing them altogether or what else?

**Comment by mayognaise** [comment]
Removing all of them but will move `aframe-gif-component`. Migration should be easy. Let me try if I can get time today... Will let you know!

**Comment by rafaeleyng** [comment]
Hmm, nice. I remember trying `aframe-gif-component` but it didn't work with transparency, as far as I remember.

**Comment by rafaeleyng** [comment]
I mean, I was using a GIF with transparency but the it was appearing with a white background.

**Comment by mayognaise** [comment]
yes because the component doesn't use `gif-shader`. i will rewrite inside of `gif-component` so that it can keep material info.

**Comment by rafaeleyng** [comment]
👍  thanks mayo

**Comment by mayognaise** [comment]
hi @rafaeleyng, sorry for the late. Now `aframe-gif-component` is ready!
https://github.com/mayognaise/aframe-gif-component
Please check the usage. Let me know if you have any question.

**Comment by rafaeleyng** [comment]
Thanks, I won't be able to test it right now, but I'll check it when I can!

**Comment by jrDev1** [comment]
Sorry to bring this up again. But is there a way to restart the gif to the first frame?

Thanks.
