### ISSUE TITLE
Unknown shader gif

### ISSUE THREAD

**Issue by devadhirath** [mayognaise/aframe-gif-shader#10]
core:a-node:error Failure loading node:   Error: "Unknown shader gif"
    Aframe 11

browser.js:111:7

It's working fine two moths ago now suddenly gif image not diplay
![Screenshot_2019-05-18 My A-Frame Scene](https://user-images.githubusercontent.com/19278615/57966548-11e50d80-7971-11e9-8d2c-5e9439c39207.png)

**Comment by mayognaise** [comment]
@devadhirath Thank you for asking.
A-frame will be update to solve this issue.
Please check this PR.
https://github.com/aframevr/aframe/pull/4167
