### ISSUE TITLE
87a GIFs aren't supported

### ISSUE THREAD

**Issue by Danpollak** [mayognaise/aframe-gif-shader#6]
87a is not supported although the formatting is similar.

changed [this line](https://github.com/mayognaise/aframe-gif-shader/blob/master/lib/gifsparser.js#L18) to 

`gif[3] === 0x38 && (gif[4] === 0x39 || gif[4] === 0x37) && gif[5] === 0x61) { // '89a'`

**Comment by mayoyml** [comment]
@Danpollak thank you so much for letting me know 🙏 
will fix it this weekend.

**Comment by mayognaise** [comment]
now `0.9.1` is here with your code. thank you so much for your contribution!
https://www.npmjs.com/package/aframe-gif-shader#contributors
